apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service-claim-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: catalog-service-claim-operator
  template:
    metadata:
      labels:
        name: catalog-service-claim-operator
    spec:
      serviceAccountName: catalog-service-claim-operator
      containers:
        - name: catalog-service-claim-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - catalog-service-claim-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "catalog-service-claim-operator"
